In [1]:
import torch

<h6><i>Тензор</i> - это многомерный вектор, например:</h6>
<h6>x = np.array([1, 2, 3]) - вектор = тензор с 1 размерностью(точнее: (3,))</h6>
<h6>y = np.array([[1, 2, 3], [4, 5, 6]]) - матрица = тензор с двумя измерениями ((2, 3) в данном случае)

### Создание тензора

In [2]:
a = torch.FloatTensor([1, 2]) # float32
print(a)
a.shape

tensor([1., 2.])


torch.Size([2])

In [3]:
b = torch.FloatTensor([[1,2,3], [4,5,6]])
print(b)
b.shape

tensor([[1., 2., 3.],
        [4., 5., 6.]])


torch.Size([2, 3])

In [4]:
x = torch.FloatTensor(2,3,4)
x

tensor([[[-2.9625e-07,  4.5733e-41, -2.9625e-07,  4.5733e-41],
         [ 1.4013e-45,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 7.7056e-36,  0.0000e+00,  2.5852e-36,  0.0000e+00],
         [ 8.2309e-16,  4.5733e-41,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]])

In [5]:
x = torch.FloatTensor(100)
x.shape

torch.Size([100])

In [6]:
x = torch.IntTensor(45, 57, 14, 2)
x.shape

torch.Size([45, 57, 14, 2])

##### Если создавать torch,Tensor то генерируются случайные числа

### Инициализация тензоров

In [7]:
x1 = torch.FloatTensor(3, 2, 4)
x2 = torch.zeros(3, 2, 4)
x3 = torch.zeros_like(x1)
x3

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
x = torch.randn((2, 3))
x

tensor([[ 0.9476, -0.2932, -0.8543],
        [ 1.5106, -0.4305,  1.9627]])

In [9]:
x.random_(0, 10) # Дискретное равномерное
x.uniform_(0, 1) # Равномерное
x.normal_(mean=0, std=1)  # норм распределение со средним 0 и дисперсией 1
x.bernoulli_(p=0.5)

tensor([[0., 0., 0.],
        [0., 1., 0.]])

### Изменение формы
##### np.reshape() == torch.view()

b

In [10]:
b.view(3, 2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [11]:
b, b.stride()

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 (3, 1))

In [12]:
b.reshape(6, 1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.]])

### Изменение типа тензора

In [16]:
a = torch.FloatTensor([1.5, 3.2, -7])
a.type_as(torch.IntTensor())

tensor([ 1,  3, -7], dtype=torch.int32)

In [17]:
a.to(torch.int32)

tensor([ 1,  3, -7], dtype=torch.int32)

  ### Фиктивные оси

In [25]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
a[:, None, :].shape

torch.Size([3, 1, 3])

In [27]:
a[:, :, None]

tensor([[[  1.],
         [  2.],
         [  3.]],

        [[ 10.],
         [ 20.],
         [ 30.]],

        [[100.],
         [200.],
         [300.]]])

In [35]:
def vertical_means(A):
    """
    param A: torch.tensor[m,n]
    """
    rows = A.shape[0]
    columns = A.shape[1]
    for col in range(columns):
         print(A[:, col].mean())
    
vertical_means(torch.FloatTensor([[2, 2, 3], [3, 4, 5]]))
            
    

tensor(2.5000)
tensor(3.)
tensor(4.)


In [39]:
def vertical_means(A):
    """
    param A: torch.tensor[m,n]
    """
    result = A.mean(dim=0)
    return result
    
A = torch.FloatTensor([[2, 2, 3], [3, 4, 5]])
vertical_means(A)            

tensor([2.3333, 4.0000])

In [57]:
def normalize_pictures(A):
    """
    param A: torch.Tensor[batch_size, num_channels, width, heigth]
    """
    m = A.mean(dim=(2, 3))
    sigma = A.std(dim=(2, 3))
    result = (A - m[:, :, None, None])/sigma[:, :, None, None]
    return result

batch = torch.randint(0, 156, (64, 3, 300, 300), dtype=torch.float32)
batch.mean(dim=(2,3)) # .shape
normalize_pictures(batch).std()

tensor(1.0000)

### Матричные операции

In [58]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [59]:
a.t()

tensor([[  1.,  10., 100.],
        [  2.,  20., 200.],
        [  3.,  30., 300.]])

In [60]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

### Скалярное произведение векторов

In [61]:
a = torch.FloatTensor([1, 2, 3, 4, 5, 6])
b = torch.FloatTensor([-1, -2, -4, -6, -8, -10])

In [63]:
a.shape, b.shape

(torch.Size([6]), torch.Size([6]))

In [64]:
 a @ b

tensor(-141.)

In [65]:
type(a)

torch.Tensor

In [66]:
type(a @ b)

torch.Tensor

### Матричное произведение

In [68]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [-100, -200, -300]])
a.mm(b)

tensor([[  -321.,   -642.,   -963.],
        [ -3210.,  -6420.,  -9630.],
        [-32100., -64200., -96300.]])

In [69]:
a @ b

tensor([[  -321.,   -642.,   -963.],
        [ -3210.,  -6420.,  -9630.],
        [-32100., -64200., -96300.]])

In [73]:
b = torch.FloatTensor([[-1], [-10], [100]])
a @ b.view(-1)

tensor([  279.,  2790., 27900.])